import { CriticalInjury } from "@/types/Types";

export const CriticalInjuries: CriticalInjury[] = [
  {
    name: "Minor Nick",
    severity: 1,
    desc: "The target suffers 1 strain.",
    image: require("@/assets/images/icons/crits/minor_nick.png"),
  },
  {
    name: "Slowed Down",
    severity: 1,
    desc: "The target can only act during the last allied Initiative slot on their next turn.",
    image: require("@/assets/images/icons/crits/slowed_down.png"),
  },
  {
    name: "Sudden Jolt",
    severity: 1,
    desc: "The target drops whatever is in hand.",
    image: require("@/assets/images/icons/crits/sudden_jolt.png"),
  },
  {
    name: "Distracted",
    severity: 1,
    desc: "The target cannot perform a free Maneuver during their next turn.",
    image: require("@/assets/images/icons/crits/distracted.png"),
  },
  {
    name: "Off-Balance",
    severity: 1,
    desc: "Add one black die to their next skill check.",
    image: require("@/assets/images/icons/crits/off_balance.png"),
  },
  {
    name: "Discouraging Wound",
    severity: 1,
    desc: "Flip one Light side Destiny point to a Dark side Destiny Point.",
    image: require("@/assets/images/icons/crits/discouraging_wound.png"),
  },
  {
    name: "Stunned",
    severity: 1,
    desc: "The target is Staggered until the end of their next turn.",
    image: require("@/assets/images/icons/crits/stunned.png"),
  },
  {
    name: "Stinger",
    severity: 1,
    desc: "Increase difficulty of next check by one.",
    image: require("@/assets/images/icons/crits/stinger.png"),
  },
  {
    name: "Bowled Over",
    severity: 2,
    desc: "The target is knocked prone and suffers 1 strain.",
    image: require("@/assets/images/icons/crits/bowled_over.png"),
  },
  {
    name: "Head Ringer",
    severity: 2,
    desc: "The target increases the difficulty of all Intellect and Cunning checks by one until the end of the encounter.",
    image: require("@/assets/images/icons/crits/head_ringer.png"),
  },
  {
    name: "Fearsome Wound",
    severity: 2,
    desc: "The target increases the difficulty of all Presence and Willpower checks by one until the end of the encounter.",
    image: require("@/assets/images/icons/crits/fearsome_wound.png"),
  },
  {
    name: "Agonizing Wound",
    severity: 2,
    desc: "The target increases the difficulty of all Brawn and Agility checks by one until the end of the encounter.",
    image: require("@/assets/images/icons/crits/agonizing_wound.png"),
  },
  {
    name: "Slightly Dazed",
    severity: 2,
    desc: "The target is disoriented until the end of the encounter.",
    image: require("@/assets/images/icons/crits/slightly_dazed.png"),
  },
  {
    name: "Scattered Senses",
    severity: 2,
    desc: "The target removes all Blue dice from skill checks until the end of the encounter.",
    image: require("@/assets/images/icons/crits/scattered_senses.png"),
  },
  {
    name: "Hamstrung",
    severity: 2,
    desc: "The target loses their free maneuver until the end of the encounter.",
    image: require("@/assets/images/icons/crits/hamstrung.png"),
  },
  {
    name: "Overpowered",
    severity: 2,
    desc: "The target leaves themselves open, and the attacker may immediately attempt another free attack against them using the exact same pool as the original attack.",
    image: require("@/assets/images/icons/crits/overpowered.png"),
  },
  {
    name: "Winded",
    severity: 2,
    desc: "Until the end of the encounter, the target cannot voluntarily suffer strain to activate any abilities or gain additional maneuvers.",
    image: require("@/assets/images/icons/crits/winded.png"),
  },
  {
    name: "Compromised",
    severity: 2,
    desc: "Increase difficulty of all skill checks by one until the end of the encounter.",
    image: require("@/assets/images/icons/crits/compromised.png"),
  },
  {
    name: "At the Brink",
    severity: 3,
    desc: "The target suffers 2 strain each time they perform an action.",
    image: require("@/assets/images/icons/crits/at_the_brink.png"),
  },
  {
    name: "Crippled",
    severity: 3,
    desc: "One of the target's limbs (selected by the GM) is crippled until healed or replaced. Increase difficulty of all checks that require use of that limb by one.",
    image: require("@/assets/images/icons/crits/crippled.png"),
  },
  {
    name: "Maimed",
    severity: 3,
    desc: "One of the target's limbs (selected by the GM) is permanently lost. Unless the target has a cybernetic or prosthetic replacement, the target cannot perform actions that would require the use of that limb. All other actions gain 1 Black die.",
    image: require("@/assets/images/icons/crits/maimed.png"),
  },
  {
    name: "Horrific Injury",
    severity: 3,
    desc: "Roll 1d10 to determine one of the target's characteristics: 1-3 for Brawn, 4-6 for Agility, 7 for Intellect, 8 for Cunning, 9 for Willpower, 10 for Presence. Until this Critical Injury is healed, treat that characteristic as one point lower.",
    image: require("@/assets/images/icons/crits/horrific_injury.png"),
  },
  {
    name: "Temporarily Lame",
    severity: 3,
    desc: "Until this Critical Injury is healed, the target cannot perform more than one maneuver in a turn.",
    image: require("@/assets/images/icons/crits/temporarily_lame.png"),
  },
  {
    name: "Blinded",
    severity: 3,
    desc: "The target can no longer see. Upgrade the difficulty of all checks twice. Upgrade the difficulty of Perception and Vigilance checks three times.",
    image: require("@/assets/images/icons/crits/blinded.png"),
  },
  {
    name: "Knocked Senseless",
    severity: 3,
    desc: "The target is staggered for the remainder of the encounter.",
    image: require("@/assets/images/icons/crits/knocked_senseless.png"),
  },
  {
    name: "Gruesome Injury",
    severity: 4,
    desc: "Roll 1d10 to determine one of the target's characteristics: 1-3 for Brawn, 4-6 for Agility, 7 for Intellect, 8 for Cunning, 9 for Willpower, 10 for Presence. Until this Critical Injury is healed, treat that characteristic as two points lower.",
    image: require("@/assets/images/icons/crits/gruesome_injury.png"),
  },
  {
    name: "Bleeding Out",
    severity: 4,
    desc: "Every round, the target suffers 1 wound and 1 strain at the beginning of their turn. For every five wounds they suffer beyond their wound threshold, they suffer one additional Critical Injury.",
    image: require("@/assets/images/icons/crits/bleeding_out.png"),
  },
  {
    name: "The End is Nigh",
    severity: 4,
    desc: "The target will die after the last Initiative slot during the next round.",
    image: require("@/assets/images/icons/crits/the_end_is_nigh.png"),
  },
  {
    name: "Dead",
    severity: 5,
    desc: "Complete, obliterated death.",
    image: require("@/assets/images/icons/crits/dead.png"),
  },
];
